<?php
    $error_codes = array(
        "1000" => array("html" => "500", "html_message" => "Internal Server Error", "message" => "Ocurrió un error interno en el servidor de Openpay"),
        "1001" => array("html" => "400", "html_message" => "Bad Request", "message" => "El formato de la petición no es JSON, los campos no tienen el formato correcto, o la petición no tiene campos que son requeridos."),
        "1002" => array("html" => "401", "html_message" => "Unauthorized", "message" => "La llamada no esta autenticada o la autenticación es incorrecta."),
        "1003" => array("html" => "422", "html_message" => "Unprocessable Entity", "message" => "La operación no se pudo completar por que el valor de uno o más de los parámetros no es correcto."),
        "1004" => array("html" => "503", "html_message" => "Service Unavailable", "message" => "Un servicio necesario para el procesamiento de la transacción no se encuentra disponible."),
        "1005" => array("html" => "404", "html_message" => "Not Found", "message" => "Uno de los recursos requeridos no existe."),
        "1006" => array("html" => "409", "html_message" => "Conflict", "message" => "Ya existe una transacción con el mismo ID de orden."),
        "1007" => array("html" => "402", "html_message" => "Payment Required", "message" => "La transferencia de fondos entre una cuenta de banco o tarjeta y la cuenta de Openpay no fue aceptada."),
        "1008" => array("html" => "423", "html_message" => "Locked", "message" => "Una de las cuentas requeridas en la petición se encuentra desactivada."),
        "1009" => array("html" => "413", "html_message" => "Request Entity too large", "message" => "El cuerpo de la petición es demasiado grande."),
        "1010" => array("html" => "403", "html_message" => "Forbidden", "message" => "Se esta utilizando la llave pública para hacer una llamada que requiere la llave privada, o bien, se esta usando la llave privada desde JavaScript."),
        "1011" => array("html" => "404", "html_message" => "Not Found", "message" => "Se solicita un recurso que esta marcado como eliminado."),
        "1012" => array("html" => "412", "html_message" => "Precondition failed", "message" => "El monto transacción esta fuera de los limites permitidos."),
        "1013" => array("html" => "412", "html_message" => "Precondition failed", "message" => "La operación no esta permitida para el recurso."),
        "1014" => array("html" => "401", "html_message" => "Unauthorized", "message" => "La cuenta esta inactiva."),
        "1015" => array("html" => "504", "html_message" => "Gateway timeout", "message" => "No se ha obtenido respuesta de la solicitud realizada al servicio."),
        "1016" => array("html" => "409", "html_message" => "Conflict", "message" => "El mail del comercio ya ha sido procesada."),
        "1017" => array("html" => "502", "html_message" => "Bad Gateway", "message" => "El gateway no se encuentra disponible en ese momento."),
        "1018" => array("html" => "402", "html_message" => "Payment Required", "message" => "El número de intentos de cargo es mayor al permitido."),
        "1020" => array("html" => "400", "html_message" => "Bad Request", "message" => "El número de dígitos decimales es inválido para esta moneda"),
        "2001" => array("html" => "409", "html_message" => "Conflict", "message" => "La cuenta de banco con esta CLABE ya se encuentra registrada en el cliente."),
        "2002" => array("html" => "409", "html_message" => "Conflict", "message" => "La tarjeta con este número ya se encuentra registrada en el cliente."),
        "2003" => array("html" => "409", "html_message" => "Conflict", "message" => "El cliente con este identificador externo (External ID) ya existe."),
        "2004" => array("html" => "422", "html_message" => "Unprocessable Entity", "message" => "El dígito verificador del número de tarjeta es inválido de acuerdo al algoritmo Luhn."),
        "2005" => array("html" => "400", "html_message" => "Bad Request", "message" => "La fecha de expiración de la tarjeta es anterior a la fecha actual."),
        "2006" => array("html" => "400", "html_message" => "Bad Request", "message" => "El código de seguridad de la tarjeta (CVV2) no fue proporcionado."),
        "2007" => array("html" => "412", "html_message" => "Precondition Failed", "message" => "El número de tarjeta es de prueba, solamente puede usarse en Sandbox."),
        "2008" => array("html" => "412", "html_message" => "Precondition Failed", "message" => "La tarjeta no es válida para puntos Santander."),
        "2009" => array("html" => "412", "html_message" => "Precondition Failed", "message" => "El código de seguridad de la tarjeta (CVV2) es inválido."),
        "2010" => array("html" => "402", "html_message" => "Payment Required", "message" => "Autenticación 3D Secure fallida."),
        "2011" => array("html" => "422", "html_message" => "Unprocessable Entity", "message" => "Tipo de tarjeta no soportada"),
        "3001" => array("html" => "402", "html_message" => "Payment Required", "message" => "La tarjeta fue declinada."),
        "3002" => array("html" => "402", "html_message" => "Payment Required", "message" => "La tarjeta ha expirado."),
        "3003" => array("html" => "402", "html_message" => "Payment Required", "message" => "La tarjeta no tiene fondos suficientes."),
        "3004" => array("html" => "402", "html_message" => "Payment Required", "message" => "La tarjeta ha sido identificada como una tarjeta robada."),
        "3005" => array("html" => "402", "html_message" => "Payment Required", "message" => "La tarjeta ha sido rechazada por el sistema antifraudes."),
        "3006" => array("html" => "412", "html_message" => "Precondition Failed", "message" => "La operación no esta permitida para este cliente o esta transacción."),
        "3007" => array("html" => "402", "html_message" => "Payment Required", "message" => "Deprecado. La tarjeta fue declinada."),
        "3008" => array("html" => "412", "html_message" => "Precondition Failed", "message" => "La tarjeta no es soportada en transacciones en línea."),
        "3009" => array("html" => "402", "html_message" => "Payment Required", "message" => "La tarjeta fue reportada como perdida."),
        "3010" => array("html" => "402", "html_message" => "Payment Required", "message" => "El banco ha restringido la tarjeta."),
        "3011" => array("html" => "402", "html_message" => "Payment Required", "message" => "El banco ha solicitado que la tarjeta sea retenida. Contacte al banco."),
        "3012" => array("html" => "412", "html_message" => "Precondition Failed", "message" => "Se requiere solicitar al banco autorización para realizar este pago."),
        "6001" => array("html" => "409", "html_message" => "Conflict", "message" => "El webhook ya ha sido procesado."),
        "6002" => array("html" => "412", "html_message" => "Preconditon Failed", "message" => "No se ha podido conectar con el servicio de webhook."),
        "6003" => array("html" => "502", "html_message" => "Bad Gateway", "message" => "El servicio respondio con errores."),
    );
?>